serverAddr = "127.0.0.1" # 请改成服务器ip
serverPort = 7000 # 服务器端口

webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"

[[proxies]]
name = "hello"
type = "tcp"
localIP = "127.0.0.1"
localPort = 2000 #本地服务端口
remotePort = 7001 #远程服务器端口, 成功部署之后, 可以通过公网ip:7001访问内网的2000端口
